# Generated by Django 4.2.9 on 2024-03-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0012_alter_coursematerial_name_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
