# Generated by Django 4.2.9 on 2024-02-16 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eLearningApp', '0009_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='materials',
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_materials/')),
                ('name', models.CharField(blank=True, help_text='Optional name for the material.', max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='eLearningApp.course')),
            ],
        ),
    ]
